# Generated by Django 3.2.5 on 2021-07-09 15:08

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(help_text='name of the doc', max_length=30, verbose_name='doc name')),
                ('doc_document', models.FileField(help_text='document', upload_to=docs.models.get_path, verbose_name='document')),
            ],
            options={
                'unique_together': {('doc_name',)},
            },
        ),
    ]
